{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    name: {{ include "app.fullname" . }}-secret
    creationPolicy: Owner
  data:
{{- toYaml .Values.externalSecrets.data | indent 4 }}
{{- end }}
