{{- if .Values.serviceAccount.create | default true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | default (dict) | indent 4 }}
{{- end }}
