{{- $sm := .Values.serviceMonitor | default (dict "enabled" false) }}
{{- if $sm.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
{{ include "app.labels" . | indent 6 }}
  endpoints:
    - port: {{ $sm.port | default "http" }}
      path: {{ $sm.path | default "/actuator/prometheus" }}
      interval: {{ $sm.interval | default "30s" }}
{{- end }}

{{- $pr := .Values.prometheusRules | default (dict "enabled" false "groups" (list)) }}
{{- if and $pr.enabled $pr.groups }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "app.fullname" . }}
spec:
  groups:
{{ toYaml $pr.groups | indent 4 }}
{{- end }}
